FROM node:19

WORKDIR /app

RUN npm install -g @angular/cli

COPY package*.json ./
RUN npm install

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll=2000", "--disable-host-check"]
